#!/bin/zsh

export vizignoref=(.gitignore)
export vizignore="node_modules|bower_components|tmp|build|dist|vendor"

ignore="$vizignore|$(echo "$@" \
    | sed -r 's/\s+/\n/g' \
    | cat `find ${vizignoref[*]} 2>/dev/null` - \
    | paste -sd\| )"

if [ "$ignore" != "" ]; then
  tree -L 4 -CI $ignore
else
  tree -C
fi

