#!/bin/sh
#
# Usage:
#
#    sh install.sh
#
# Environment variables: VERBOSE, CP, LN, MKDIR, RM, DIRNAME.
#
#    env VERBOSE=1 sh install.sh
#
# DO NOT EDIT THIS FILE
# 
# This file is generated by rcm(7) as:
#
#   rcup -B 0 -g
#
# To update it, re-run the above command.
#
: ${VERBOSE:=0}
: ${CP:=/bin/cp}
: ${LN:=/bin/ln}
: ${MKDIR:=/bin/mkdir}
: ${RM:=/bin/rm}
: ${DIRNAME:=/usr/bin/dirname}
verbose() {
  if [ "$VERBOSE" -gt 0 ]; then
    echo "$@"
  fi
}
handle_file_cp() {
  if [ -e "$2" ]; then
    printf "%s " "overwrite $2? [yN]"
    read overwrite
    case "$overwrite" in
      y)
        $RM -rf "$2"
        ;;
      *)
        echo "skipping $2"
        return
        ;;
    esac
  fi
  verbose "'$1' -> '$2'"
  $MKDIR -p "$($DIRNAME "$2")"
  $CP -R "$1" "$2"
}
handle_file_ln() {
  if [ -e "$2" ]; then
    printf "%s " "overwrite $2? [yN]"
    read overwrite
    case "$overwrite" in
      y)
        $RM -rf "$2"
        ;;
      *)
        echo "skipping $2"
        return
        ;;
    esac
  fi
  verbose "'$1' -> '$2'"
  $MKDIR -p "$($DIRNAME "$2")"
  $LN -sf "$1" "$2"
}
handle_file_ln "/home/fluffywaffles/.dotfiles/aliases" "/home/fluffywaffles/.aliases"
handle_file_ln "/home/fluffywaffles/.dotfiles/bashrc" "/home/fluffywaffles/.bashrc"
handle_file_ln "/home/fluffywaffles/.dotfiles/config/bspwm/bspwmrc" "/home/fluffywaffles/.config/bspwm/bspwmrc"
handle_file_ln "/home/fluffywaffles/.dotfiles/config/sxhkd/sxhkdrc" "/home/fluffywaffles/.config/sxhkd/sxhkdrc"
handle_file_ln "/home/fluffywaffles/.dotfiles/config/user-dirs.dirs" "/home/fluffywaffles/.config/user-dirs.dirs"
handle_file_ln "/home/fluffywaffles/.dotfiles/config/user-dirs.locale" "/home/fluffywaffles/.config/user-dirs.locale"
handle_file_ln "/home/fluffywaffles/.dotfiles/feh-set-background" "/home/fluffywaffles/.feh-set-background"
handle_file_ln "/home/fluffywaffles/.dotfiles/gitconfig" "/home/fluffywaffles/.gitconfig"
handle_file_ln "/home/fluffywaffles/.dotfiles/install.sh" "/home/fluffywaffles/.install.sh"
handle_file_ln "/home/fluffywaffles/.dotfiles/install-st.sh" "/home/fluffywaffles/.install-st.sh"
handle_file_ln "/home/fluffywaffles/.dotfiles/local/bin/dims" "/home/fluffywaffles/.local/bin/dims"
handle_file_ln "/home/fluffywaffles/.dotfiles/local/bin/height" "/home/fluffywaffles/.local/bin/height"
handle_file_ln "/home/fluffywaffles/.dotfiles/local/bin/jira" "/home/fluffywaffles/.local/bin/jira"
handle_file_ln "/home/fluffywaffles/.dotfiles/local/bin/monitor-info" "/home/fluffywaffles/.local/bin/monitor-info"
handle_file_ln "/home/fluffywaffles/.dotfiles/local/bin/screenshot" "/home/fluffywaffles/.local/bin/screenshot"
handle_file_ln "/home/fluffywaffles/.dotfiles/local/bin/slack" "/home/fluffywaffles/.local/bin/slack"
handle_file_ln "/home/fluffywaffles/.dotfiles/local/bin/width" "/home/fluffywaffles/.local/bin/width"
handle_file_ln "/home/fluffywaffles/.dotfiles/profile" "/home/fluffywaffles/.profile"
handle_file_ln "/home/fluffywaffles/.dotfiles/ssh/config" "/home/fluffywaffles/.ssh/config"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/3024 Day.h" "/home/fluffywaffles/.st-colors/3024 Day.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/3024 Night.h" "/home/fluffywaffles/.st-colors/3024 Night.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/AdventureTime.h" "/home/fluffywaffles/.st-colors/AdventureTime.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Afterglow.h" "/home/fluffywaffles/.st-colors/Afterglow.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/AlienBlood.h" "/home/fluffywaffles/.st-colors/AlienBlood.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Argonaut.h" "/home/fluffywaffles/.st-colors/Argonaut.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Arthur.h" "/home/fluffywaffles/.st-colors/Arthur.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/AtelierSulphurpool.h" "/home/fluffywaffles/.st-colors/AtelierSulphurpool.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Atom.h" "/home/fluffywaffles/.st-colors/Atom.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/AtomOneLight.h" "/home/fluffywaffles/.st-colors/AtomOneLight.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Batman.h" "/home/fluffywaffles/.st-colors/Batman.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Belafonte Day.h" "/home/fluffywaffles/.st-colors/Belafonte Day.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Belafonte Night.h" "/home/fluffywaffles/.st-colors/Belafonte Night.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/BirdsOfParadise.h" "/home/fluffywaffles/.st-colors/BirdsOfParadise.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Blazer.h" "/home/fluffywaffles/.st-colors/Blazer.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Borland.h" "/home/fluffywaffles/.st-colors/Borland.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Bright Lights.h" "/home/fluffywaffles/.st-colors/Bright Lights.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Broadcast.h" "/home/fluffywaffles/.st-colors/Broadcast.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Brogrammer.h" "/home/fluffywaffles/.st-colors/Brogrammer.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/C64.h" "/home/fluffywaffles/.st-colors/C64.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Chalkboard.h" "/home/fluffywaffles/.st-colors/Chalkboard.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Chalk.h" "/home/fluffywaffles/.st-colors/Chalk.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Ciapre.h" "/home/fluffywaffles/.st-colors/Ciapre.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/CLRS.h" "/home/fluffywaffles/.st-colors/CLRS.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Cobalt2.h" "/home/fluffywaffles/.st-colors/Cobalt2.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Cobalt Neon.h" "/home/fluffywaffles/.st-colors/Cobalt Neon.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/CrayonPonyFish.h" "/home/fluffywaffles/.st-colors/CrayonPonyFish.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Dark Pastel.h" "/home/fluffywaffles/.st-colors/Dark Pastel.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Darkside.h" "/home/fluffywaffles/.st-colors/Darkside.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Desert.h" "/home/fluffywaffles/.st-colors/Desert.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/DimmedMonokai.h" "/home/fluffywaffles/.st-colors/DimmedMonokai.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/DotGov.h" "/home/fluffywaffles/.st-colors/DotGov.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Dracula.h" "/home/fluffywaffles/.st-colors/Dracula.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Duotone Dark.h" "/home/fluffywaffles/.st-colors/Duotone Dark.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Earthsong.h" "/home/fluffywaffles/.st-colors/Earthsong.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Elemental.h" "/home/fluffywaffles/.st-colors/Elemental.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/ENCOM.h" "/home/fluffywaffles/.st-colors/ENCOM.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Espresso.h" "/home/fluffywaffles/.st-colors/Espresso.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Espresso Libre.h" "/home/fluffywaffles/.st-colors/Espresso Libre.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Fideloper.h" "/home/fluffywaffles/.st-colors/Fideloper.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/FishTank.h" "/home/fluffywaffles/.st-colors/FishTank.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Flat.h" "/home/fluffywaffles/.st-colors/Flat.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Flatland.h" "/home/fluffywaffles/.st-colors/Flatland.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Floraverse.h" "/home/fluffywaffles/.st-colors/Floraverse.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/FrontEndDelight.h" "/home/fluffywaffles/.st-colors/FrontEndDelight.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/FunForrest.h" "/home/fluffywaffles/.st-colors/FunForrest.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Galaxy.h" "/home/fluffywaffles/.st-colors/Galaxy.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Github.h" "/home/fluffywaffles/.st-colors/Github.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Glacier.h" "/home/fluffywaffles/.st-colors/Glacier.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Grape.h" "/home/fluffywaffles/.st-colors/Grape.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Grass.h" "/home/fluffywaffles/.st-colors/Grass.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Hardcore.h" "/home/fluffywaffles/.st-colors/Hardcore.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Harper.h" "/home/fluffywaffles/.st-colors/Harper.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Highway.h" "/home/fluffywaffles/.st-colors/Highway.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Hipster Green.h" "/home/fluffywaffles/.st-colors/Hipster Green.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Homebrew.h" "/home/fluffywaffles/.st-colors/Homebrew.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Hurtado.h" "/home/fluffywaffles/.st-colors/Hurtado.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Hybrid.h" "/home/fluffywaffles/.st-colors/Hybrid.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/IC_Green_PPL.h" "/home/fluffywaffles/.st-colors/IC_Green_PPL.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/IC_Orange_PPL.h" "/home/fluffywaffles/.st-colors/IC_Orange_PPL.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/idleToes.h" "/home/fluffywaffles/.st-colors/idleToes.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/IR_Black.h" "/home/fluffywaffles/.st-colors/IR_Black.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Jackie Brown.h" "/home/fluffywaffles/.st-colors/Jackie Brown.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Japanesque.h" "/home/fluffywaffles/.st-colors/Japanesque.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Jellybeans.h" "/home/fluffywaffles/.st-colors/Jellybeans.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/JetBrains Darcula.h" "/home/fluffywaffles/.st-colors/JetBrains Darcula.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Kibble.h" "/home/fluffywaffles/.st-colors/Kibble.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Later This Evening.h" "/home/fluffywaffles/.st-colors/Later This Evening.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Lavandula.h" "/home/fluffywaffles/.st-colors/Lavandula.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/LiquidCarbon.h" "/home/fluffywaffles/.st-colors/LiquidCarbon.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/LiquidCarbonTransparent.h" "/home/fluffywaffles/.st-colors/LiquidCarbonTransparent.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/LiquidCarbonTransparentInverse.h" "/home/fluffywaffles/.st-colors/LiquidCarbonTransparentInverse.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Man Page.h" "/home/fluffywaffles/.st-colors/Man Page.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/MaterialDark.h" "/home/fluffywaffles/.st-colors/MaterialDark.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Material.h" "/home/fluffywaffles/.st-colors/Material.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Mathias.h" "/home/fluffywaffles/.st-colors/Mathias.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Medallion.h" "/home/fluffywaffles/.st-colors/Medallion.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Misterioso.h" "/home/fluffywaffles/.st-colors/Misterioso.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Molokai.h" "/home/fluffywaffles/.st-colors/Molokai.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/MonaLisa.h" "/home/fluffywaffles/.st-colors/MonaLisa.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Monokai Soda.h" "/home/fluffywaffles/.st-colors/Monokai Soda.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/N0tch2k.h" "/home/fluffywaffles/.st-colors/N0tch2k.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Neopolitan.h" "/home/fluffywaffles/.st-colors/Neopolitan.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Neutron.h" "/home/fluffywaffles/.st-colors/Neutron.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/NightLion v1.h" "/home/fluffywaffles/.st-colors/NightLion v1.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/NightLion v2.h" "/home/fluffywaffles/.st-colors/NightLion v2.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Novel.h" "/home/fluffywaffles/.st-colors/Novel.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Obsidian.h" "/home/fluffywaffles/.st-colors/Obsidian.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Ocean.h" "/home/fluffywaffles/.st-colors/Ocean.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/OceanicMaterial.h" "/home/fluffywaffles/.st-colors/OceanicMaterial.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Ollie.h" "/home/fluffywaffles/.st-colors/Ollie.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Parasio Dark.h" "/home/fluffywaffles/.st-colors/Parasio Dark.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/PaulMillr.h" "/home/fluffywaffles/.st-colors/PaulMillr.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/PencilDark.h" "/home/fluffywaffles/.st-colors/PencilDark.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/PencilLight.h" "/home/fluffywaffles/.st-colors/PencilLight.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Piatto Light.h" "/home/fluffywaffles/.st-colors/Piatto Light.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Pnevma.h" "/home/fluffywaffles/.st-colors/Pnevma.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Pro.h" "/home/fluffywaffles/.st-colors/Pro.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Red Alert.h" "/home/fluffywaffles/.st-colors/Red Alert.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Red Sands.h" "/home/fluffywaffles/.st-colors/Red Sands.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Rippedcasts.h" "/home/fluffywaffles/.st-colors/Rippedcasts.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Royal.h" "/home/fluffywaffles/.st-colors/Royal.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Seafoam Pastel.h" "/home/fluffywaffles/.st-colors/Seafoam Pastel.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/SeaShells.h" "/home/fluffywaffles/.st-colors/SeaShells.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Seti.h" "/home/fluffywaffles/.st-colors/Seti.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Shaman.h" "/home/fluffywaffles/.st-colors/Shaman.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Slate.h" "/home/fluffywaffles/.st-colors/Slate.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Smyck.h" "/home/fluffywaffles/.st-colors/Smyck.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/SoftServer.h" "/home/fluffywaffles/.st-colors/SoftServer.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Solarized Darcula.h" "/home/fluffywaffles/.st-colors/Solarized Darcula.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Solarized Dark.h" "/home/fluffywaffles/.st-colors/Solarized Dark.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Solarized Dark Higher Contrast.h" "/home/fluffywaffles/.st-colors/Solarized Dark Higher Contrast.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Solarized Dark - Patched.h" "/home/fluffywaffles/.st-colors/Solarized Dark - Patched.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Solarized Light.h" "/home/fluffywaffles/.st-colors/Solarized Light.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Spacedust.h" "/home/fluffywaffles/.st-colors/Spacedust.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/SpaceGray Eighties Dull.h" "/home/fluffywaffles/.st-colors/SpaceGray Eighties Dull.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/SpaceGray Eighties.h" "/home/fluffywaffles/.st-colors/SpaceGray Eighties.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/SpaceGray.h" "/home/fluffywaffles/.st-colors/SpaceGray.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Spiderman.h" "/home/fluffywaffles/.st-colors/Spiderman.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Spring.h" "/home/fluffywaffles/.st-colors/Spring.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Square.h" "/home/fluffywaffles/.st-colors/Square.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Sundried.h" "/home/fluffywaffles/.st-colors/Sundried.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Symfonic.h" "/home/fluffywaffles/.st-colors/Symfonic.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Teerb.h" "/home/fluffywaffles/.st-colors/Teerb.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Terminal Basic.h" "/home/fluffywaffles/.st-colors/Terminal Basic.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Thayer Bright.h" "/home/fluffywaffles/.st-colors/Thayer Bright.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/The Hulk.h" "/home/fluffywaffles/.st-colors/The Hulk.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Tomorrow.h" "/home/fluffywaffles/.st-colors/Tomorrow.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Tomorrow Night Blue.h" "/home/fluffywaffles/.st-colors/Tomorrow Night Blue.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Tomorrow Night Bright.h" "/home/fluffywaffles/.st-colors/Tomorrow Night Bright.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Tomorrow Night Eighties.h" "/home/fluffywaffles/.st-colors/Tomorrow Night Eighties.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Tomorrow Night.h" "/home/fluffywaffles/.st-colors/Tomorrow Night.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/ToyChest.h" "/home/fluffywaffles/.st-colors/ToyChest.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Treehouse.h" "/home/fluffywaffles/.st-colors/Treehouse.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Twilight.h" "/home/fluffywaffles/.st-colors/Twilight.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Ubuntu.h" "/home/fluffywaffles/.st-colors/Ubuntu.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Urple.h" "/home/fluffywaffles/.st-colors/Urple.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Vaughn.h" "/home/fluffywaffles/.st-colors/Vaughn.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/VibrantInk.h" "/home/fluffywaffles/.st-colors/VibrantInk.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/WarmNeon.h" "/home/fluffywaffles/.st-colors/WarmNeon.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Wez.h" "/home/fluffywaffles/.st-colors/Wez.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/WildCherry.h" "/home/fluffywaffles/.st-colors/WildCherry.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Wombat.h" "/home/fluffywaffles/.st-colors/Wombat.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Wryan.h" "/home/fluffywaffles/.st-colors/Wryan.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-colors/Zenburn.h" "/home/fluffywaffles/.st-colors/Zenburn.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/st-config.h" "/home/fluffywaffles/.st-config.h"
handle_file_ln "/home/fluffywaffles/.dotfiles/terminfo/s/st" "/home/fluffywaffles/.terminfo/s/st"
handle_file_ln "/home/fluffywaffles/.dotfiles/terminfo/s/st-256color" "/home/fluffywaffles/.terminfo/s/st-256color"
handle_file_ln "/home/fluffywaffles/.dotfiles/terminfo/s/st-meta" "/home/fluffywaffles/.terminfo/s/st-meta"
handle_file_ln "/home/fluffywaffles/.dotfiles/terminfo/s/st-meta-256color" "/home/fluffywaffles/.terminfo/s/st-meta-256color"
handle_file_ln "/home/fluffywaffles/.dotfiles/tmux.conf" "/home/fluffywaffles/.tmux.conf"
handle_file_ln "/home/fluffywaffles/.dotfiles/xinitrc" "/home/fluffywaffles/.xinitrc"
handle_file_ln "/home/fluffywaffles/.dotfiles/Xresources" "/home/fluffywaffles/.Xresources"
handle_file_ln "/home/fluffywaffles/.dotfiles/zshrc" "/home/fluffywaffles/.zshrc"
handle_file_ln "/home/fluffywaffles/.dotfiles/zshrc.local" "/home/fluffywaffles/.zshrc.local"
