#!/bin/sh
#
# Usage:
#
#    sh install.sh <path-to-home>
#
# Environment variables: VERBOSE, CP, LN, MKDIR, RM, DIRNAME.
#
#    env VERBOSE=1 sh install.sh
#
# DO NOT EDIT THIS FILE
# 
# This file is generated by rcm(7) as:
#
#   rcup -B 0 -g
#
# To update it, re-run the above command.
#
#
: ${VERBOSE:=0}
: ${CP:=/bin/cp}
: ${LN:=/bin/ln}
: ${MKDIR:=/bin/mkdir}
: ${RM:=/bin/rm}
: ${DIRNAME:=/usr/bin/dirname}
verbose() {
  if [ "$VERBOSE" -gt 0 ]; then
    echo "$@"
  fi
}
handle_file_cp() {
  if [ -e "$2" ]; then
    printf "%s " "overwrite $2? [yN]"
    read overwrite
    case "$overwrite" in
      y)
        $RM -rf "$2"
        ;;
      *)
        echo "skipping $2"
        return
        ;;
    esac
  fi
  verbose "'$1' -> '$2'"
  $MKDIR -p "$($DIRNAME "$2")"
  $CP -R "$1" "$2"
}
handle_file_ln() {
  if [ -e "$2" ]; then
    printf "%s " "overwrite $2? [yN]"
    read overwrite
    case "$overwrite" in
      y)
        $RM -rf "$2"
        ;;
      *)
        echo "skipping $2"
        return
        ;;
    esac
  fi
  verbose "'$1' -> '$2'"
  $MKDIR -p "$($DIRNAME "$2")"
  $LN -sf "$1" "$2"
}
handle_file_ln "$1/.dotfiles/aliases" "$1/.aliases"
handle_file_ln "$1/.dotfiles/bashrc" "$1/.bashrc"
handle_file_ln "$1/.dotfiles/config/bspwm/bspwmrc" "$1/.config/bspwm/bspwmrc"
handle_file_ln "$1/.dotfiles/config/sxhkd/sxhkdrc" "$1/.config/sxhkd/sxhkdrc"
handle_file_ln "$1/.dotfiles/config/user-dirs.dirs" "$1/.config/user-dirs.dirs"
handle_file_ln "$1/.dotfiles/config/user-dirs.locale" "$1/.config/user-dirs.locale"
handle_file_ln "$1/.dotfiles/feh-set-background" "$1/.feh-set-background"
handle_file_ln "$1/.dotfiles/gitconfig" "$1/.gitconfig"
handle_file_ln "$1/.dotfiles/install.sh" "$1/.install.sh"
handle_file_ln "$1/.dotfiles/install-st.sh" "$1/.install-st.sh"
handle_file_ln "$1/.dotfiles/local/bin/dims" "$1/.local/bin/dims"
handle_file_ln "$1/.dotfiles/local/bin/height" "$1/.local/bin/height"
handle_file_ln "$1/.dotfiles/local/bin/jira" "$1/.local/bin/jira"
handle_file_ln "$1/.dotfiles/local/bin/monitor-info" "$1/.local/bin/monitor-info"
handle_file_ln "$1/.dotfiles/local/bin/screenshot" "$1/.local/bin/screenshot"
handle_file_ln "$1/.dotfiles/local/bin/slack" "$1/.local/bin/slack"
handle_file_ln "$1/.dotfiles/local/bin/width" "$1/.local/bin/width"
handle_file_ln "$1/.dotfiles/profile" "$1/.profile"
handle_file_ln "$1/.dotfiles/ssh/config" "$1/.ssh/config"
handle_file_ln "$1/.dotfiles/st-colors/3024 Day.h" "$1/.st-colors/3024 Day.h"
handle_file_ln "$1/.dotfiles/st-colors/3024 Night.h" "$1/.st-colors/3024 Night.h"
handle_file_ln "$1/.dotfiles/st-colors/AdventureTime.h" "$1/.st-colors/AdventureTime.h"
handle_file_ln "$1/.dotfiles/st-colors/Afterglow.h" "$1/.st-colors/Afterglow.h"
handle_file_ln "$1/.dotfiles/st-colors/AlienBlood.h" "$1/.st-colors/AlienBlood.h"
handle_file_ln "$1/.dotfiles/st-colors/Argonaut.h" "$1/.st-colors/Argonaut.h"
handle_file_ln "$1/.dotfiles/st-colors/Arthur.h" "$1/.st-colors/Arthur.h"
handle_file_ln "$1/.dotfiles/st-colors/AtelierSulphurpool.h" "$1/.st-colors/AtelierSulphurpool.h"
handle_file_ln "$1/.dotfiles/st-colors/Atom.h" "$1/.st-colors/Atom.h"
handle_file_ln "$1/.dotfiles/st-colors/AtomOneLight.h" "$1/.st-colors/AtomOneLight.h"
handle_file_ln "$1/.dotfiles/st-colors/Batman.h" "$1/.st-colors/Batman.h"
handle_file_ln "$1/.dotfiles/st-colors/Belafonte Day.h" "$1/.st-colors/Belafonte Day.h"
handle_file_ln "$1/.dotfiles/st-colors/Belafonte Night.h" "$1/.st-colors/Belafonte Night.h"
handle_file_ln "$1/.dotfiles/st-colors/BirdsOfParadise.h" "$1/.st-colors/BirdsOfParadise.h"
handle_file_ln "$1/.dotfiles/st-colors/Blazer.h" "$1/.st-colors/Blazer.h"
handle_file_ln "$1/.dotfiles/st-colors/Borland.h" "$1/.st-colors/Borland.h"
handle_file_ln "$1/.dotfiles/st-colors/Bright Lights.h" "$1/.st-colors/Bright Lights.h"
handle_file_ln "$1/.dotfiles/st-colors/Broadcast.h" "$1/.st-colors/Broadcast.h"
handle_file_ln "$1/.dotfiles/st-colors/Brogrammer.h" "$1/.st-colors/Brogrammer.h"
handle_file_ln "$1/.dotfiles/st-colors/C64.h" "$1/.st-colors/C64.h"
handle_file_ln "$1/.dotfiles/st-colors/Chalkboard.h" "$1/.st-colors/Chalkboard.h"
handle_file_ln "$1/.dotfiles/st-colors/Chalk.h" "$1/.st-colors/Chalk.h"
handle_file_ln "$1/.dotfiles/st-colors/Ciapre.h" "$1/.st-colors/Ciapre.h"
handle_file_ln "$1/.dotfiles/st-colors/CLRS.h" "$1/.st-colors/CLRS.h"
handle_file_ln "$1/.dotfiles/st-colors/Cobalt2.h" "$1/.st-colors/Cobalt2.h"
handle_file_ln "$1/.dotfiles/st-colors/Cobalt Neon.h" "$1/.st-colors/Cobalt Neon.h"
handle_file_ln "$1/.dotfiles/st-colors/CrayonPonyFish.h" "$1/.st-colors/CrayonPonyFish.h"
handle_file_ln "$1/.dotfiles/st-colors/Dark Pastel.h" "$1/.st-colors/Dark Pastel.h"
handle_file_ln "$1/.dotfiles/st-colors/Darkside.h" "$1/.st-colors/Darkside.h"
handle_file_ln "$1/.dotfiles/st-colors/Desert.h" "$1/.st-colors/Desert.h"
handle_file_ln "$1/.dotfiles/st-colors/DimmedMonokai.h" "$1/.st-colors/DimmedMonokai.h"
handle_file_ln "$1/.dotfiles/st-colors/DotGov.h" "$1/.st-colors/DotGov.h"
handle_file_ln "$1/.dotfiles/st-colors/Dracula.h" "$1/.st-colors/Dracula.h"
handle_file_ln "$1/.dotfiles/st-colors/Duotone Dark.h" "$1/.st-colors/Duotone Dark.h"
handle_file_ln "$1/.dotfiles/st-colors/Earthsong.h" "$1/.st-colors/Earthsong.h"
handle_file_ln "$1/.dotfiles/st-colors/Elemental.h" "$1/.st-colors/Elemental.h"
handle_file_ln "$1/.dotfiles/st-colors/ENCOM.h" "$1/.st-colors/ENCOM.h"
handle_file_ln "$1/.dotfiles/st-colors/Espresso.h" "$1/.st-colors/Espresso.h"
handle_file_ln "$1/.dotfiles/st-colors/Espresso Libre.h" "$1/.st-colors/Espresso Libre.h"
handle_file_ln "$1/.dotfiles/st-colors/Fideloper.h" "$1/.st-colors/Fideloper.h"
handle_file_ln "$1/.dotfiles/st-colors/FishTank.h" "$1/.st-colors/FishTank.h"
handle_file_ln "$1/.dotfiles/st-colors/Flat.h" "$1/.st-colors/Flat.h"
handle_file_ln "$1/.dotfiles/st-colors/Flatland.h" "$1/.st-colors/Flatland.h"
handle_file_ln "$1/.dotfiles/st-colors/Floraverse.h" "$1/.st-colors/Floraverse.h"
handle_file_ln "$1/.dotfiles/st-colors/FrontEndDelight.h" "$1/.st-colors/FrontEndDelight.h"
handle_file_ln "$1/.dotfiles/st-colors/FunForrest.h" "$1/.st-colors/FunForrest.h"
handle_file_ln "$1/.dotfiles/st-colors/Galaxy.h" "$1/.st-colors/Galaxy.h"
handle_file_ln "$1/.dotfiles/st-colors/Github.h" "$1/.st-colors/Github.h"
handle_file_ln "$1/.dotfiles/st-colors/Glacier.h" "$1/.st-colors/Glacier.h"
handle_file_ln "$1/.dotfiles/st-colors/Grape.h" "$1/.st-colors/Grape.h"
handle_file_ln "$1/.dotfiles/st-colors/Grass.h" "$1/.st-colors/Grass.h"
handle_file_ln "$1/.dotfiles/st-colors/Hardcore.h" "$1/.st-colors/Hardcore.h"
handle_file_ln "$1/.dotfiles/st-colors/Harper.h" "$1/.st-colors/Harper.h"
handle_file_ln "$1/.dotfiles/st-colors/Highway.h" "$1/.st-colors/Highway.h"
handle_file_ln "$1/.dotfiles/st-colors/Hipster Green.h" "$1/.st-colors/Hipster Green.h"
handle_file_ln "$1/.dotfiles/st-colors/Homebrew.h" "$1/.st-colors/Homebrew.h"
handle_file_ln "$1/.dotfiles/st-colors/Hurtado.h" "$1/.st-colors/Hurtado.h"
handle_file_ln "$1/.dotfiles/st-colors/Hybrid.h" "$1/.st-colors/Hybrid.h"
handle_file_ln "$1/.dotfiles/st-colors/IC_Green_PPL.h" "$1/.st-colors/IC_Green_PPL.h"
handle_file_ln "$1/.dotfiles/st-colors/IC_Orange_PPL.h" "$1/.st-colors/IC_Orange_PPL.h"
handle_file_ln "$1/.dotfiles/st-colors/idleToes.h" "$1/.st-colors/idleToes.h"
handle_file_ln "$1/.dotfiles/st-colors/IR_Black.h" "$1/.st-colors/IR_Black.h"
handle_file_ln "$1/.dotfiles/st-colors/Jackie Brown.h" "$1/.st-colors/Jackie Brown.h"
handle_file_ln "$1/.dotfiles/st-colors/Japanesque.h" "$1/.st-colors/Japanesque.h"
handle_file_ln "$1/.dotfiles/st-colors/Jellybeans.h" "$1/.st-colors/Jellybeans.h"
handle_file_ln "$1/.dotfiles/st-colors/JetBrains Darcula.h" "$1/.st-colors/JetBrains Darcula.h"
handle_file_ln "$1/.dotfiles/st-colors/Kibble.h" "$1/.st-colors/Kibble.h"
handle_file_ln "$1/.dotfiles/st-colors/Later This Evening.h" "$1/.st-colors/Later This Evening.h"
handle_file_ln "$1/.dotfiles/st-colors/Lavandula.h" "$1/.st-colors/Lavandula.h"
handle_file_ln "$1/.dotfiles/st-colors/LiquidCarbon.h" "$1/.st-colors/LiquidCarbon.h"
handle_file_ln "$1/.dotfiles/st-colors/LiquidCarbonTransparent.h" "$1/.st-colors/LiquidCarbonTransparent.h"
handle_file_ln "$1/.dotfiles/st-colors/LiquidCarbonTransparentInverse.h" "$1/.st-colors/LiquidCarbonTransparentInverse.h"
handle_file_ln "$1/.dotfiles/st-colors/Man Page.h" "$1/.st-colors/Man Page.h"
handle_file_ln "$1/.dotfiles/st-colors/MaterialDark.h" "$1/.st-colors/MaterialDark.h"
handle_file_ln "$1/.dotfiles/st-colors/Material.h" "$1/.st-colors/Material.h"
handle_file_ln "$1/.dotfiles/st-colors/Mathias.h" "$1/.st-colors/Mathias.h"
handle_file_ln "$1/.dotfiles/st-colors/Medallion.h" "$1/.st-colors/Medallion.h"
handle_file_ln "$1/.dotfiles/st-colors/Misterioso.h" "$1/.st-colors/Misterioso.h"
handle_file_ln "$1/.dotfiles/st-colors/Molokai.h" "$1/.st-colors/Molokai.h"
handle_file_ln "$1/.dotfiles/st-colors/MonaLisa.h" "$1/.st-colors/MonaLisa.h"
handle_file_ln "$1/.dotfiles/st-colors/Monokai Soda.h" "$1/.st-colors/Monokai Soda.h"
handle_file_ln "$1/.dotfiles/st-colors/N0tch2k.h" "$1/.st-colors/N0tch2k.h"
handle_file_ln "$1/.dotfiles/st-colors/Neopolitan.h" "$1/.st-colors/Neopolitan.h"
handle_file_ln "$1/.dotfiles/st-colors/Neutron.h" "$1/.st-colors/Neutron.h"
handle_file_ln "$1/.dotfiles/st-colors/NightLion v1.h" "$1/.st-colors/NightLion v1.h"
handle_file_ln "$1/.dotfiles/st-colors/NightLion v2.h" "$1/.st-colors/NightLion v2.h"
handle_file_ln "$1/.dotfiles/st-colors/Novel.h" "$1/.st-colors/Novel.h"
handle_file_ln "$1/.dotfiles/st-colors/Obsidian.h" "$1/.st-colors/Obsidian.h"
handle_file_ln "$1/.dotfiles/st-colors/Ocean.h" "$1/.st-colors/Ocean.h"
handle_file_ln "$1/.dotfiles/st-colors/OceanicMaterial.h" "$1/.st-colors/OceanicMaterial.h"
handle_file_ln "$1/.dotfiles/st-colors/Ollie.h" "$1/.st-colors/Ollie.h"
handle_file_ln "$1/.dotfiles/st-colors/Parasio Dark.h" "$1/.st-colors/Parasio Dark.h"
handle_file_ln "$1/.dotfiles/st-colors/PaulMillr.h" "$1/.st-colors/PaulMillr.h"
handle_file_ln "$1/.dotfiles/st-colors/PencilDark.h" "$1/.st-colors/PencilDark.h"
handle_file_ln "$1/.dotfiles/st-colors/PencilLight.h" "$1/.st-colors/PencilLight.h"
handle_file_ln "$1/.dotfiles/st-colors/Piatto Light.h" "$1/.st-colors/Piatto Light.h"
handle_file_ln "$1/.dotfiles/st-colors/Pnevma.h" "$1/.st-colors/Pnevma.h"
handle_file_ln "$1/.dotfiles/st-colors/Pro.h" "$1/.st-colors/Pro.h"
handle_file_ln "$1/.dotfiles/st-colors/Red Alert.h" "$1/.st-colors/Red Alert.h"
handle_file_ln "$1/.dotfiles/st-colors/Red Sands.h" "$1/.st-colors/Red Sands.h"
handle_file_ln "$1/.dotfiles/st-colors/Rippedcasts.h" "$1/.st-colors/Rippedcasts.h"
handle_file_ln "$1/.dotfiles/st-colors/Royal.h" "$1/.st-colors/Royal.h"
handle_file_ln "$1/.dotfiles/st-colors/Seafoam Pastel.h" "$1/.st-colors/Seafoam Pastel.h"
handle_file_ln "$1/.dotfiles/st-colors/SeaShells.h" "$1/.st-colors/SeaShells.h"
handle_file_ln "$1/.dotfiles/st-colors/Seti.h" "$1/.st-colors/Seti.h"
handle_file_ln "$1/.dotfiles/st-colors/Shaman.h" "$1/.st-colors/Shaman.h"
handle_file_ln "$1/.dotfiles/st-colors/Slate.h" "$1/.st-colors/Slate.h"
handle_file_ln "$1/.dotfiles/st-colors/Smyck.h" "$1/.st-colors/Smyck.h"
handle_file_ln "$1/.dotfiles/st-colors/SoftServer.h" "$1/.st-colors/SoftServer.h"
handle_file_ln "$1/.dotfiles/st-colors/Solarized Darcula.h" "$1/.st-colors/Solarized Darcula.h"
handle_file_ln "$1/.dotfiles/st-colors/Solarized Dark.h" "$1/.st-colors/Solarized Dark.h"
handle_file_ln "$1/.dotfiles/st-colors/Solarized Dark Higher Contrast.h" "$1/.st-colors/Solarized Dark Higher Contrast.h"
handle_file_ln "$1/.dotfiles/st-colors/Solarized Dark - Patched.h" "$1/.st-colors/Solarized Dark - Patched.h"
handle_file_ln "$1/.dotfiles/st-colors/Solarized Light.h" "$1/.st-colors/Solarized Light.h"
handle_file_ln "$1/.dotfiles/st-colors/Spacedust.h" "$1/.st-colors/Spacedust.h"
handle_file_ln "$1/.dotfiles/st-colors/SpaceGray Eighties Dull.h" "$1/.st-colors/SpaceGray Eighties Dull.h"
handle_file_ln "$1/.dotfiles/st-colors/SpaceGray Eighties.h" "$1/.st-colors/SpaceGray Eighties.h"
handle_file_ln "$1/.dotfiles/st-colors/SpaceGray.h" "$1/.st-colors/SpaceGray.h"
handle_file_ln "$1/.dotfiles/st-colors/Spiderman.h" "$1/.st-colors/Spiderman.h"
handle_file_ln "$1/.dotfiles/st-colors/Spring.h" "$1/.st-colors/Spring.h"
handle_file_ln "$1/.dotfiles/st-colors/Square.h" "$1/.st-colors/Square.h"
handle_file_ln "$1/.dotfiles/st-colors/Sundried.h" "$1/.st-colors/Sundried.h"
handle_file_ln "$1/.dotfiles/st-colors/Symfonic.h" "$1/.st-colors/Symfonic.h"
handle_file_ln "$1/.dotfiles/st-colors/Teerb.h" "$1/.st-colors/Teerb.h"
handle_file_ln "$1/.dotfiles/st-colors/Terminal Basic.h" "$1/.st-colors/Terminal Basic.h"
handle_file_ln "$1/.dotfiles/st-colors/Thayer Bright.h" "$1/.st-colors/Thayer Bright.h"
handle_file_ln "$1/.dotfiles/st-colors/The Hulk.h" "$1/.st-colors/The Hulk.h"
handle_file_ln "$1/.dotfiles/st-colors/Tomorrow.h" "$1/.st-colors/Tomorrow.h"
handle_file_ln "$1/.dotfiles/st-colors/Tomorrow Night Blue.h" "$1/.st-colors/Tomorrow Night Blue.h"
handle_file_ln "$1/.dotfiles/st-colors/Tomorrow Night Bright.h" "$1/.st-colors/Tomorrow Night Bright.h"
handle_file_ln "$1/.dotfiles/st-colors/Tomorrow Night Eighties.h" "$1/.st-colors/Tomorrow Night Eighties.h"
handle_file_ln "$1/.dotfiles/st-colors/Tomorrow Night.h" "$1/.st-colors/Tomorrow Night.h"
handle_file_ln "$1/.dotfiles/st-colors/ToyChest.h" "$1/.st-colors/ToyChest.h"
handle_file_ln "$1/.dotfiles/st-colors/Treehouse.h" "$1/.st-colors/Treehouse.h"
handle_file_ln "$1/.dotfiles/st-colors/Twilight.h" "$1/.st-colors/Twilight.h"
handle_file_ln "$1/.dotfiles/st-colors/Ubuntu.h" "$1/.st-colors/Ubuntu.h"
handle_file_ln "$1/.dotfiles/st-colors/Urple.h" "$1/.st-colors/Urple.h"
handle_file_ln "$1/.dotfiles/st-colors/Vaughn.h" "$1/.st-colors/Vaughn.h"
handle_file_ln "$1/.dotfiles/st-colors/VibrantInk.h" "$1/.st-colors/VibrantInk.h"
handle_file_ln "$1/.dotfiles/st-colors/WarmNeon.h" "$1/.st-colors/WarmNeon.h"
handle_file_ln "$1/.dotfiles/st-colors/Wez.h" "$1/.st-colors/Wez.h"
handle_file_ln "$1/.dotfiles/st-colors/WildCherry.h" "$1/.st-colors/WildCherry.h"
handle_file_ln "$1/.dotfiles/st-colors/Wombat.h" "$1/.st-colors/Wombat.h"
handle_file_ln "$1/.dotfiles/st-colors/Wryan.h" "$1/.st-colors/Wryan.h"
handle_file_ln "$1/.dotfiles/st-colors/Zenburn.h" "$1/.st-colors/Zenburn.h"
handle_file_ln "$1/.dotfiles/st-config.h" "$1/.st-config.h"
handle_file_ln "$1/.dotfiles/terminfo/s/st" "$1/.terminfo/s/st"
handle_file_ln "$1/.dotfiles/terminfo/s/st-256color" "$1/.terminfo/s/st-256color"
handle_file_ln "$1/.dotfiles/terminfo/s/st-meta" "$1/.terminfo/s/st-meta"
handle_file_ln "$1/.dotfiles/terminfo/s/st-meta-256color" "$1/.terminfo/s/st-meta-256color"
handle_file_ln "$1/.dotfiles/tmux.conf" "$1/.tmux.conf"
handle_file_ln "$1/.dotfiles/xinitrc" "$1/.xinitrc"
handle_file_ln "$1/.dotfiles/Xresources" "$1/.Xresources"
handle_file_ln "$1/.dotfiles/zshrc" "$1/.zshrc"
handle_file_ln "$1/.dotfiles/zshrc.local" "$1/.zshrc.local"
