#!/bin/sh
#
# Usage:
#
#    sh install.sh
#
# Environment variables: VERBOSE, CP, LN, MKDIR, RM, DIRNAME.
#
#    env VERBOSE=1 sh install.sh
#
# DO NOT EDIT THIS FILE
# 
# This file is generated by rcm(7) as:
#
#   rcup -B 0 -g
#
# To update it, re-run the above command.
#
: ${VERBOSE:=0}
: ${CP:=/bin/cp}
: ${LN:=/bin/ln}
: ${MKDIR:=/bin/mkdir}
: ${RM:=/bin/rm}
: ${DIRNAME:=/usr/bin/dirname}
verbose() {
  if [ "$VERBOSE" -gt 0 ]; then
    echo "$@"
  fi
}
handle_file_cp() {
  if [ -e "$2" ]; then
    printf "%s " "overwrite $2? [yN]"
    read overwrite
    case "$overwrite" in
      y)
        $RM -rf "$2"
        ;;
      *)
        echo "skipping $2"
        return
        ;;
    esac
  fi
  verbose "'$1' -> '$2'"
  $MKDIR -p "$($DIRNAME "$2")"
  $CP -R "$1" "$2"
}
handle_file_ln() {
  if [ -e "$2" ]; then
    printf "%s " "overwrite $2? [yN]"
    read overwrite
    case "$overwrite" in
      y)
        $RM -rf "$2"
        ;;
      *)
        echo "skipping $2"
        return
        ;;
    esac
  fi
  verbose "'$1' -> '$2'"
  $MKDIR -p "$($DIRNAME "$2")"
  $LN -sf "$1" "$2"
}
handle_file_ln "~/.dotfiles/aliases" "~/.aliases"
handle_file_ln "~/.dotfiles/bashrc" "~/.bashrc"
handle_file_ln "~/.dotfiles/config/bspwm/bspwmrc" "~/.config/bspwm/bspwmrc"
handle_file_ln "~/.dotfiles/config/sxhkd/sxhkdrc" "~/.config/sxhkd/sxhkdrc"
handle_file_ln "~/.dotfiles/config/user-dirs.dirs" "~/.config/user-dirs.dirs"
handle_file_ln "~/.dotfiles/config/user-dirs.locale" "~/.config/user-dirs.locale"
handle_file_ln "~/.dotfiles/feh-set-background" "~/.feh-set-background"
handle_file_ln "~/.dotfiles/gitconfig" "~/.gitconfig"
handle_file_ln "~/.dotfiles/install.sh" "~/.install.sh"
handle_file_ln "~/.dotfiles/install-st.sh" "~/.install-st.sh"
handle_file_ln "~/.dotfiles/local/bin/dims" "~/.local/bin/dims"
handle_file_ln "~/.dotfiles/local/bin/height" "~/.local/bin/height"
handle_file_ln "~/.dotfiles/local/bin/jira" "~/.local/bin/jira"
handle_file_ln "~/.dotfiles/local/bin/monitor-info" "~/.local/bin/monitor-info"
handle_file_ln "~/.dotfiles/local/bin/screenshot" "~/.local/bin/screenshot"
handle_file_ln "~/.dotfiles/local/bin/slack" "~/.local/bin/slack"
handle_file_ln "~/.dotfiles/local/bin/width" "~/.local/bin/width"
handle_file_ln "~/.dotfiles/profile" "~/.profile"
handle_file_ln "~/.dotfiles/ssh/config" "~/.ssh/config"
handle_file_ln "~/.dotfiles/st-colors/3024 Day.h" "~/.st-colors/3024 Day.h"
handle_file_ln "~/.dotfiles/st-colors/3024 Night.h" "~/.st-colors/3024 Night.h"
handle_file_ln "~/.dotfiles/st-colors/AdventureTime.h" "~/.st-colors/AdventureTime.h"
handle_file_ln "~/.dotfiles/st-colors/Afterglow.h" "~/.st-colors/Afterglow.h"
handle_file_ln "~/.dotfiles/st-colors/AlienBlood.h" "~/.st-colors/AlienBlood.h"
handle_file_ln "~/.dotfiles/st-colors/Argonaut.h" "~/.st-colors/Argonaut.h"
handle_file_ln "~/.dotfiles/st-colors/Arthur.h" "~/.st-colors/Arthur.h"
handle_file_ln "~/.dotfiles/st-colors/AtelierSulphurpool.h" "~/.st-colors/AtelierSulphurpool.h"
handle_file_ln "~/.dotfiles/st-colors/Atom.h" "~/.st-colors/Atom.h"
handle_file_ln "~/.dotfiles/st-colors/AtomOneLight.h" "~/.st-colors/AtomOneLight.h"
handle_file_ln "~/.dotfiles/st-colors/Batman.h" "~/.st-colors/Batman.h"
handle_file_ln "~/.dotfiles/st-colors/Belafonte Day.h" "~/.st-colors/Belafonte Day.h"
handle_file_ln "~/.dotfiles/st-colors/Belafonte Night.h" "~/.st-colors/Belafonte Night.h"
handle_file_ln "~/.dotfiles/st-colors/BirdsOfParadise.h" "~/.st-colors/BirdsOfParadise.h"
handle_file_ln "~/.dotfiles/st-colors/Blazer.h" "~/.st-colors/Blazer.h"
handle_file_ln "~/.dotfiles/st-colors/Borland.h" "~/.st-colors/Borland.h"
handle_file_ln "~/.dotfiles/st-colors/Bright Lights.h" "~/.st-colors/Bright Lights.h"
handle_file_ln "~/.dotfiles/st-colors/Broadcast.h" "~/.st-colors/Broadcast.h"
handle_file_ln "~/.dotfiles/st-colors/Brogrammer.h" "~/.st-colors/Brogrammer.h"
handle_file_ln "~/.dotfiles/st-colors/C64.h" "~/.st-colors/C64.h"
handle_file_ln "~/.dotfiles/st-colors/Chalkboard.h" "~/.st-colors/Chalkboard.h"
handle_file_ln "~/.dotfiles/st-colors/Chalk.h" "~/.st-colors/Chalk.h"
handle_file_ln "~/.dotfiles/st-colors/Ciapre.h" "~/.st-colors/Ciapre.h"
handle_file_ln "~/.dotfiles/st-colors/CLRS.h" "~/.st-colors/CLRS.h"
handle_file_ln "~/.dotfiles/st-colors/Cobalt2.h" "~/.st-colors/Cobalt2.h"
handle_file_ln "~/.dotfiles/st-colors/Cobalt Neon.h" "~/.st-colors/Cobalt Neon.h"
handle_file_ln "~/.dotfiles/st-colors/CrayonPonyFish.h" "~/.st-colors/CrayonPonyFish.h"
handle_file_ln "~/.dotfiles/st-colors/Dark Pastel.h" "~/.st-colors/Dark Pastel.h"
handle_file_ln "~/.dotfiles/st-colors/Darkside.h" "~/.st-colors/Darkside.h"
handle_file_ln "~/.dotfiles/st-colors/Desert.h" "~/.st-colors/Desert.h"
handle_file_ln "~/.dotfiles/st-colors/DimmedMonokai.h" "~/.st-colors/DimmedMonokai.h"
handle_file_ln "~/.dotfiles/st-colors/DotGov.h" "~/.st-colors/DotGov.h"
handle_file_ln "~/.dotfiles/st-colors/Dracula.h" "~/.st-colors/Dracula.h"
handle_file_ln "~/.dotfiles/st-colors/Duotone Dark.h" "~/.st-colors/Duotone Dark.h"
handle_file_ln "~/.dotfiles/st-colors/Earthsong.h" "~/.st-colors/Earthsong.h"
handle_file_ln "~/.dotfiles/st-colors/Elemental.h" "~/.st-colors/Elemental.h"
handle_file_ln "~/.dotfiles/st-colors/ENCOM.h" "~/.st-colors/ENCOM.h"
handle_file_ln "~/.dotfiles/st-colors/Espresso.h" "~/.st-colors/Espresso.h"
handle_file_ln "~/.dotfiles/st-colors/Espresso Libre.h" "~/.st-colors/Espresso Libre.h"
handle_file_ln "~/.dotfiles/st-colors/Fideloper.h" "~/.st-colors/Fideloper.h"
handle_file_ln "~/.dotfiles/st-colors/FishTank.h" "~/.st-colors/FishTank.h"
handle_file_ln "~/.dotfiles/st-colors/Flat.h" "~/.st-colors/Flat.h"
handle_file_ln "~/.dotfiles/st-colors/Flatland.h" "~/.st-colors/Flatland.h"
handle_file_ln "~/.dotfiles/st-colors/Floraverse.h" "~/.st-colors/Floraverse.h"
handle_file_ln "~/.dotfiles/st-colors/FrontEndDelight.h" "~/.st-colors/FrontEndDelight.h"
handle_file_ln "~/.dotfiles/st-colors/FunForrest.h" "~/.st-colors/FunForrest.h"
handle_file_ln "~/.dotfiles/st-colors/Galaxy.h" "~/.st-colors/Galaxy.h"
handle_file_ln "~/.dotfiles/st-colors/Github.h" "~/.st-colors/Github.h"
handle_file_ln "~/.dotfiles/st-colors/Glacier.h" "~/.st-colors/Glacier.h"
handle_file_ln "~/.dotfiles/st-colors/Grape.h" "~/.st-colors/Grape.h"
handle_file_ln "~/.dotfiles/st-colors/Grass.h" "~/.st-colors/Grass.h"
handle_file_ln "~/.dotfiles/st-colors/Hardcore.h" "~/.st-colors/Hardcore.h"
handle_file_ln "~/.dotfiles/st-colors/Harper.h" "~/.st-colors/Harper.h"
handle_file_ln "~/.dotfiles/st-colors/Highway.h" "~/.st-colors/Highway.h"
handle_file_ln "~/.dotfiles/st-colors/Hipster Green.h" "~/.st-colors/Hipster Green.h"
handle_file_ln "~/.dotfiles/st-colors/Homebrew.h" "~/.st-colors/Homebrew.h"
handle_file_ln "~/.dotfiles/st-colors/Hurtado.h" "~/.st-colors/Hurtado.h"
handle_file_ln "~/.dotfiles/st-colors/Hybrid.h" "~/.st-colors/Hybrid.h"
handle_file_ln "~/.dotfiles/st-colors/IC_Green_PPL.h" "~/.st-colors/IC_Green_PPL.h"
handle_file_ln "~/.dotfiles/st-colors/IC_Orange_PPL.h" "~/.st-colors/IC_Orange_PPL.h"
handle_file_ln "~/.dotfiles/st-colors/idleToes.h" "~/.st-colors/idleToes.h"
handle_file_ln "~/.dotfiles/st-colors/IR_Black.h" "~/.st-colors/IR_Black.h"
handle_file_ln "~/.dotfiles/st-colors/Jackie Brown.h" "~/.st-colors/Jackie Brown.h"
handle_file_ln "~/.dotfiles/st-colors/Japanesque.h" "~/.st-colors/Japanesque.h"
handle_file_ln "~/.dotfiles/st-colors/Jellybeans.h" "~/.st-colors/Jellybeans.h"
handle_file_ln "~/.dotfiles/st-colors/JetBrains Darcula.h" "~/.st-colors/JetBrains Darcula.h"
handle_file_ln "~/.dotfiles/st-colors/Kibble.h" "~/.st-colors/Kibble.h"
handle_file_ln "~/.dotfiles/st-colors/Later This Evening.h" "~/.st-colors/Later This Evening.h"
handle_file_ln "~/.dotfiles/st-colors/Lavandula.h" "~/.st-colors/Lavandula.h"
handle_file_ln "~/.dotfiles/st-colors/LiquidCarbon.h" "~/.st-colors/LiquidCarbon.h"
handle_file_ln "~/.dotfiles/st-colors/LiquidCarbonTransparent.h" "~/.st-colors/LiquidCarbonTransparent.h"
handle_file_ln "~/.dotfiles/st-colors/LiquidCarbonTransparentInverse.h" "~/.st-colors/LiquidCarbonTransparentInverse.h"
handle_file_ln "~/.dotfiles/st-colors/Man Page.h" "~/.st-colors/Man Page.h"
handle_file_ln "~/.dotfiles/st-colors/MaterialDark.h" "~/.st-colors/MaterialDark.h"
handle_file_ln "~/.dotfiles/st-colors/Material.h" "~/.st-colors/Material.h"
handle_file_ln "~/.dotfiles/st-colors/Mathias.h" "~/.st-colors/Mathias.h"
handle_file_ln "~/.dotfiles/st-colors/Medallion.h" "~/.st-colors/Medallion.h"
handle_file_ln "~/.dotfiles/st-colors/Misterioso.h" "~/.st-colors/Misterioso.h"
handle_file_ln "~/.dotfiles/st-colors/Molokai.h" "~/.st-colors/Molokai.h"
handle_file_ln "~/.dotfiles/st-colors/MonaLisa.h" "~/.st-colors/MonaLisa.h"
handle_file_ln "~/.dotfiles/st-colors/Monokai Soda.h" "~/.st-colors/Monokai Soda.h"
handle_file_ln "~/.dotfiles/st-colors/N0tch2k.h" "~/.st-colors/N0tch2k.h"
handle_file_ln "~/.dotfiles/st-colors/Neopolitan.h" "~/.st-colors/Neopolitan.h"
handle_file_ln "~/.dotfiles/st-colors/Neutron.h" "~/.st-colors/Neutron.h"
handle_file_ln "~/.dotfiles/st-colors/NightLion v1.h" "~/.st-colors/NightLion v1.h"
handle_file_ln "~/.dotfiles/st-colors/NightLion v2.h" "~/.st-colors/NightLion v2.h"
handle_file_ln "~/.dotfiles/st-colors/Novel.h" "~/.st-colors/Novel.h"
handle_file_ln "~/.dotfiles/st-colors/Obsidian.h" "~/.st-colors/Obsidian.h"
handle_file_ln "~/.dotfiles/st-colors/Ocean.h" "~/.st-colors/Ocean.h"
handle_file_ln "~/.dotfiles/st-colors/OceanicMaterial.h" "~/.st-colors/OceanicMaterial.h"
handle_file_ln "~/.dotfiles/st-colors/Ollie.h" "~/.st-colors/Ollie.h"
handle_file_ln "~/.dotfiles/st-colors/Parasio Dark.h" "~/.st-colors/Parasio Dark.h"
handle_file_ln "~/.dotfiles/st-colors/PaulMillr.h" "~/.st-colors/PaulMillr.h"
handle_file_ln "~/.dotfiles/st-colors/PencilDark.h" "~/.st-colors/PencilDark.h"
handle_file_ln "~/.dotfiles/st-colors/PencilLight.h" "~/.st-colors/PencilLight.h"
handle_file_ln "~/.dotfiles/st-colors/Piatto Light.h" "~/.st-colors/Piatto Light.h"
handle_file_ln "~/.dotfiles/st-colors/Pnevma.h" "~/.st-colors/Pnevma.h"
handle_file_ln "~/.dotfiles/st-colors/Pro.h" "~/.st-colors/Pro.h"
handle_file_ln "~/.dotfiles/st-colors/Red Alert.h" "~/.st-colors/Red Alert.h"
handle_file_ln "~/.dotfiles/st-colors/Red Sands.h" "~/.st-colors/Red Sands.h"
handle_file_ln "~/.dotfiles/st-colors/Rippedcasts.h" "~/.st-colors/Rippedcasts.h"
handle_file_ln "~/.dotfiles/st-colors/Royal.h" "~/.st-colors/Royal.h"
handle_file_ln "~/.dotfiles/st-colors/Seafoam Pastel.h" "~/.st-colors/Seafoam Pastel.h"
handle_file_ln "~/.dotfiles/st-colors/SeaShells.h" "~/.st-colors/SeaShells.h"
handle_file_ln "~/.dotfiles/st-colors/Seti.h" "~/.st-colors/Seti.h"
handle_file_ln "~/.dotfiles/st-colors/Shaman.h" "~/.st-colors/Shaman.h"
handle_file_ln "~/.dotfiles/st-colors/Slate.h" "~/.st-colors/Slate.h"
handle_file_ln "~/.dotfiles/st-colors/Smyck.h" "~/.st-colors/Smyck.h"
handle_file_ln "~/.dotfiles/st-colors/SoftServer.h" "~/.st-colors/SoftServer.h"
handle_file_ln "~/.dotfiles/st-colors/Solarized Darcula.h" "~/.st-colors/Solarized Darcula.h"
handle_file_ln "~/.dotfiles/st-colors/Solarized Dark.h" "~/.st-colors/Solarized Dark.h"
handle_file_ln "~/.dotfiles/st-colors/Solarized Dark Higher Contrast.h" "~/.st-colors/Solarized Dark Higher Contrast.h"
handle_file_ln "~/.dotfiles/st-colors/Solarized Dark - Patched.h" "~/.st-colors/Solarized Dark - Patched.h"
handle_file_ln "~/.dotfiles/st-colors/Solarized Light.h" "~/.st-colors/Solarized Light.h"
handle_file_ln "~/.dotfiles/st-colors/Spacedust.h" "~/.st-colors/Spacedust.h"
handle_file_ln "~/.dotfiles/st-colors/SpaceGray Eighties Dull.h" "~/.st-colors/SpaceGray Eighties Dull.h"
handle_file_ln "~/.dotfiles/st-colors/SpaceGray Eighties.h" "~/.st-colors/SpaceGray Eighties.h"
handle_file_ln "~/.dotfiles/st-colors/SpaceGray.h" "~/.st-colors/SpaceGray.h"
handle_file_ln "~/.dotfiles/st-colors/Spiderman.h" "~/.st-colors/Spiderman.h"
handle_file_ln "~/.dotfiles/st-colors/Spring.h" "~/.st-colors/Spring.h"
handle_file_ln "~/.dotfiles/st-colors/Square.h" "~/.st-colors/Square.h"
handle_file_ln "~/.dotfiles/st-colors/Sundried.h" "~/.st-colors/Sundried.h"
handle_file_ln "~/.dotfiles/st-colors/Symfonic.h" "~/.st-colors/Symfonic.h"
handle_file_ln "~/.dotfiles/st-colors/Teerb.h" "~/.st-colors/Teerb.h"
handle_file_ln "~/.dotfiles/st-colors/Terminal Basic.h" "~/.st-colors/Terminal Basic.h"
handle_file_ln "~/.dotfiles/st-colors/Thayer Bright.h" "~/.st-colors/Thayer Bright.h"
handle_file_ln "~/.dotfiles/st-colors/The Hulk.h" "~/.st-colors/The Hulk.h"
handle_file_ln "~/.dotfiles/st-colors/Tomorrow.h" "~/.st-colors/Tomorrow.h"
handle_file_ln "~/.dotfiles/st-colors/Tomorrow Night Blue.h" "~/.st-colors/Tomorrow Night Blue.h"
handle_file_ln "~/.dotfiles/st-colors/Tomorrow Night Bright.h" "~/.st-colors/Tomorrow Night Bright.h"
handle_file_ln "~/.dotfiles/st-colors/Tomorrow Night Eighties.h" "~/.st-colors/Tomorrow Night Eighties.h"
handle_file_ln "~/.dotfiles/st-colors/Tomorrow Night.h" "~/.st-colors/Tomorrow Night.h"
handle_file_ln "~/.dotfiles/st-colors/ToyChest.h" "~/.st-colors/ToyChest.h"
handle_file_ln "~/.dotfiles/st-colors/Treehouse.h" "~/.st-colors/Treehouse.h"
handle_file_ln "~/.dotfiles/st-colors/Twilight.h" "~/.st-colors/Twilight.h"
handle_file_ln "~/.dotfiles/st-colors/Ubuntu.h" "~/.st-colors/Ubuntu.h"
handle_file_ln "~/.dotfiles/st-colors/Urple.h" "~/.st-colors/Urple.h"
handle_file_ln "~/.dotfiles/st-colors/Vaughn.h" "~/.st-colors/Vaughn.h"
handle_file_ln "~/.dotfiles/st-colors/VibrantInk.h" "~/.st-colors/VibrantInk.h"
handle_file_ln "~/.dotfiles/st-colors/WarmNeon.h" "~/.st-colors/WarmNeon.h"
handle_file_ln "~/.dotfiles/st-colors/Wez.h" "~/.st-colors/Wez.h"
handle_file_ln "~/.dotfiles/st-colors/WildCherry.h" "~/.st-colors/WildCherry.h"
handle_file_ln "~/.dotfiles/st-colors/Wombat.h" "~/.st-colors/Wombat.h"
handle_file_ln "~/.dotfiles/st-colors/Wryan.h" "~/.st-colors/Wryan.h"
handle_file_ln "~/.dotfiles/st-colors/Zenburn.h" "~/.st-colors/Zenburn.h"
handle_file_ln "~/.dotfiles/st-config.h" "~/.st-config.h"
handle_file_ln "~/.dotfiles/terminfo/s/st" "~/.terminfo/s/st"
handle_file_ln "~/.dotfiles/terminfo/s/st-256color" "~/.terminfo/s/st-256color"
handle_file_ln "~/.dotfiles/terminfo/s/st-meta" "~/.terminfo/s/st-meta"
handle_file_ln "~/.dotfiles/terminfo/s/st-meta-256color" "~/.terminfo/s/st-meta-256color"
handle_file_ln "~/.dotfiles/tmux.conf" "~/.tmux.conf"
handle_file_ln "~/.dotfiles/xinitrc" "~/.xinitrc"
handle_file_ln "~/.dotfiles/Xresources" "~/.Xresources"
handle_file_ln "~/.dotfiles/zshrc" "~/.zshrc"
handle_file_ln "~/.dotfiles/zshrc.local" "~/.zshrc.local"
