#! /bin/sh
bspc monitor -d I II III IV V

bspc config border_width    0
bspc config window_gap      0
bspc config top_padding    20
bspc config left_padding   20
bspc config right_padding  20
bspc config bottom_padding 20

bspc config split_ratio        0.50

bspc config borderless_monocle true
bspc config gapless_monocle    true

bspc config pointer_follows_focus true
bspc config click_to_focus        button1

bspc config center_pseudo_tiled true
