#!/bin/bash -e

##
# Connect to WiFi.
##
# Requires
#   wpa_passphrase
#   wpa_supplicant
#   dhcpcd
#   sudo
##
# Usage
#   Install in `${HOME}/@`; i.e.: `${HOME}/@/connect`
#
#   Add a WiFi configuration using:
#     $ wpa_passphrase {ssid} {passphrase} > ${HOME}/@/{name}.conf
#
#   Symlink this script as @/{name}:
#     $ ln -s ${HOME}/@/connect ${HOME}/@/{name}
#
#   To connect:
#     $ ~/@/{name}
#
#   If prompted, enter password for `sudo`.
##
if [[ $(id -u) -ne 0 ]]; then
	exec sudo $0
fi

pkill wpa_supplicant
pkill dhcpcd
directory=$(dirname $0)
conf_name=$(basename $0)

set -x
wpa_supplicant -Bi wlp2s0 -c ${directory}/${conf_name}.conf
dhcpcd wlp2s0
